language: haxe

haxe:
  - "3.2.1"
  - development

hxml:
  - build.hxml

os:
  - linux
  - osx

sudo: false
addons:
  apt:
    packages:
     - python-pip

before_install:
  - git clone https://github.com/andyli/pyextern.git ../pyextern
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    sudo easy_install pip;
    fi
  - pip install --user conda
  - conda env create -f environment.yml
  - source activate env