language: haxe

haxe:
  - "3.2.1"
  - development

hxml:
  - build.hxml

sudo: required
dist: trusty

addons:
  apt:
    packages:
     - python3
     - python3-pip

before_install:
  - git clone https://github.com/andyli/pyextern.git ../pyextern
  - pip3 install -r requirements.txt