language: haxe

haxe:
  - "3.2.1"
  - development

hxml:
  - build.hxml

sudo: false
addons:
  apt:
    packages:
     - python-pip

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - git clone https://github.com/andyli/pyextern.git ../pyextern
  - pip install --user conda
  - conda env create -f environment.yml

before_script:
  - source activate env