name: haxe-usage-survey
dependencies:
- freetype=2.5.5
- libpng=1.6.17
- matplotlib=1.4.3
- numpy=1.10.1
- openssl=1.0.2d
- pandas=0.17.0
- pip=7.1.2
- pyparsing=2.0.3
- pyqt=4.11.4
- python=3.5.0
- python-dateutil=2.4.2
- pytz=2015.6
- qt=4.8.7
- readline=6.2
- scipy=0.16.0
- seaborn=0.6.0
- setuptools=18.4
- sip=4.16.9
- six=1.10.0
- sqlite=3.8.4.1
- tk=8.5.18
- wheel=0.26.0
- xz=5.0.5
- zlib=1.2.8
